### PR TITLE
added followers and following

### PR DESCRIPTION
**Pull request by haarsh24**

### CODE REVIEW

**Comment by shashikantmaurya0007** [comment]
looks good to be merged

**Review by shashikantmaurya0007 — COMMENTED** [review]
looks good to be merged

**Comment by xii-vi** [comment]
Please provide a description of the PR.
Overall Code Structure is godd

**Review by xii-vi — COMMENTED** [review]
**Try to minimize the number of code changes in a single PR and also provide a description for the same.**

**Pull request merged**
